# bringup_py/config/domain_bridge_arm_cmd.yaml
name: arm_domain_bridge

topics:
  # PC(20) -> 로봇(21,31,32) : /arm/cmd
  /arm/cmd:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 21
  /arm/cmd:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 31
  /arm/cmd:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 32

  # 로봇(21,31,32) -> PC(20) : /arm/state
  /arm/state:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 21
    to_domain: 20
  /arm/state:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 31
    to_domain: 20
  /arm/state:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 32
    to_domain: 20

  # PC(20) -> 로봇(21,31,32) : /arm/pose_cmd
  /arm/pose_cmd:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 21
  /arm/pose_cmd:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 31
  /arm/pose_cmd:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 32

  # PC(20) -> 로봇(21,31,32) : /arm/target_px (cx, cy, w, h)
  /arm/target_px:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 21
  /arm/target_px:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 31
  /arm/target_px:
    type: std_msgs/msg/Float32MultiArray
    from_domain: 20
    to_domain: 32
